// This program outputs the lyrics for the Twelve Days of Christmas. The program
// 'sings' two versions, the original version of the song and the "rustic"
// version of the song with rust-themed gifts. The rustic version of the lyrics
// were generated by Chat-GPT.

// Jason Gullifer 2023

// Happy Holidays!

use std::io;
use std::io::prelude::*;

fn get_title(rust_version: bool) -> String {
    // Function to get the title of the song depending on whether the rustic version is requested
    let addition = if rust_version {
        " (Rustic)"
    } else {
        ""
    };
    format!("The Twelve{addition} Days of Christmas\nSung by Rust")
}

fn get_gifts(rust_version :bool) -> [&'static str; 12]  {
    // Function to get the gifts depending on whether the rustic version is requested
    if rust_version { // rust-themed gifts, generated with the help of chat-gpt
        [
            "a borrow checker in a pear tree",
            "two lifetime annotations",
            "three ownership models",
            "four fearless concurrency primitives",
            "five pattern matching arms",
            "six iterators iterating",
            "seven crates a-cargo-ing",
            "eight lifetimes a-lending",
            "nine macros expanding",
            "ten structs a-defining",
            "eleven trait implementations",
            "twelve async tasks a-awaiting",
        ]
    } else{ // regular gifts
        [
            "a partridge in a pear tree",
            "two turtle doves",
            "three French hens",
            "four calling birds",
            "five golden rings",
            "six geese a-laying",
            "seven swans a-swimming",
            "eight maids a-milking",
            "nine ladies dancing",
            "ten lords a-leaping",
            "eleven pipers piping",
            "twelve drummers drumming",
        ]
    }
}

fn sing(rust_version :bool) {
    // Function to sing the song
    let days:  [&str; 12] = ["first", "second", "third", "fourth", "fifth", "sixth", "seventh", "eighth", "ninth", "tenth", "eleventh", "twelfth"];
    let title: String = get_title(rust_version);
    let gifts: [&'static str; 12] = get_gifts(rust_version);
    let ndays = days.len();

    println!("\n{title}");
    println!("===============================================");
    for day in 0..ndays{
        println!("");
        let cur_day = days[day];
        let cur_gift = gifts[day];
        let refrain = format!("On the {cur_day} day of Christmas my true love gave to me {cur_gift}");
        let refrain = if day == 0 {
            format!("{refrain}.")
        } else if day == 1{
            format!("{refrain}")
        } else {
            format!("{refrain}, ")
        };
        
            println!("{refrain}");
            if day > 0{
            for inner_day in (1..=day).rev(){
                let inner_gift = gifts[inner_day-1];
                if inner_day > 1 {
                    println!("{inner_gift},");
                } else{
                    println!("and {inner_gift}.");
                }                            
            }
        }
    }
    println!("");
    println!("");
}

fn pause() {
    // Function to wait for the user to press enter. This was copied from Rust help forums (user DroidLogician).
    let mut stdin = io::stdin();
    let mut stdout = io::stdout();

    // We want the cursor to stay at the end of the line, so we print without a newline and flush manually.
    write!(stdout, "Press Enter key to close the command line...").unwrap();
    stdout.flush().unwrap();

    // Read a single byte and discard
    let _ = stdin.read(&mut [0u8]).unwrap();
}

fn main() {
    // run the program! sing the regular version of the song, followed by the rustic version, the pause before quitting
    loop{
        print!("Which version of The Twelve Days of Christmas do you want?\n(1) Standard Version; (2) Rustic Version; Other Key to Quit: ");
        io::stdout().flush().unwrap();
        let mut choice = String::new();

        io::stdin()
        .read_line(&mut choice)
        .expect("Failed to read line!");

        let choice: u8 = match choice.trim().parse() {
            Ok(num) => num,
            Err(_) => {                
                0          
            }
        };

        if choice == 1 {
            sing(false);
            
        } else if choice == 2 {
            sing(true);
            
        } else{
            println!("Quitting program.");
            pause();
            break;
        }
        
    }

}